import { Container, Spacer } from "@nextui-org/react";
import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Suggestions from "../components/Suggestions";
import { Subject } from "../interfaces/subject";

const Home = ({ subjects }) => {
  return (
    <Container fluid xl>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header title="Simple Upvote" />
      <main>
        <Spacer y={2} />
        <Suggestions subjects={subjects} />
      </main>
    </Container>
  );
};

Home.getInitialProps = async () => {
  const res = await axios.get<Subject[]>("http://localhost:5001/api/subjects");
  const { data } = res;

  return { subjects: data };
};

export default Home;
