import { Badge } from "@nextui-org/react";
import axios from "axios";
import Head from "next/head";

const Home = ({ subjects }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <div>
          <ul>
            {subjects.map((subject) => (
              <li key={subject.id}>
                <Badge displayName>{subject.name}</Badge>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

Home.getInitialProps = async () => {
  const res = await axios.get("http://localhost:5001/api/subjects");
  const { data } = res;

  return { subjects: data };
};

export default Home;
